server:
  port: 8989
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/blog?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  # 配置文件上传大小限制
  servlet:
    multipart:
      max-file-size: 10MB    #上传文件的最大大小
      max-request-size: 20MB #整个请求（包括文件和其他表单字段）的最大大小
  redis:
    host: 192.168.12.128
    port: 6379
    password: redis
    database: 0
    timeout: 100000
mybatis-plus:
  configuration:
    # 日志
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto
minio:
  endpoint: http://192.168.12.128:9000 #Minio服务所在地址
  accessKey: minioadmin #访问的用户名
  secretKey: minioadmin #密码
  bucketName: blog #存储桶名称
